# .travis.yml

language: r
warnings_are_errors: true #to skip for now warnings about data size & compression
dist: trusty
cache: packages

r:
#  - oldrel
  - release
#  - devel




notifications:
 email:
   on_success: change
   on_failure: change
